name: Percy batch tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install --save-dev @percy/cli
      - run: npx percy snapshot tests/batch_comparison/snapshots.yml # or any directory such as public/
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_BATCH }}
